In [1]:
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
digits = load_digits()


In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size= 0.3)

In [3]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9592592592592593

In [4]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9611111111111111

In [5]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9796296296296296

In [35]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 3)


In [32]:
# logic of kfold
kf1 = KFold(n_splits= 5)
for train, test in kf1.split([0,1,2,3,4,5]):
    print(train, test)

[2 3 4 5] [0 1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]


In [31]:
def model_eval(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [36]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits= 4)
score_l = []
score_random =[]
score_svc = []

for train, test in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train], digits.data[test], digits.target[train], digits.target[test]
    score_l.append(model_eval(LogisticRegression(), x_train, x_test, y_train, y_test))
    score_random.append(model_eval(RandomForestClassifier(), x_train, x_test, y_train, y_test))
    score_svc.append(model_eval(SVC(), x_train, x_test, y_train, y_test))
print("logistic score", score_l)
print("RandomForestClassifier score", score_random)
print("SVC", score_svc)


logistic score [0.9232053422370617, 0.9415692821368948, 0.9148580968280468]
RandomForestClassifier score [0.9298831385642737, 0.9549248747913188, 0.9181969949916527]
SVC [0.9666110183639399, 0.9816360601001669, 0.9549248747913188]


In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(LogisticRegression(), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [39]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93611111, 0.90277778, 0.95821727, 0.95821727, 0.93314763])

In [40]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [44]:
print("10", cross_val_score(RandomForestClassifier(10), digits.data, digits.target))
print("20", cross_val_score(RandomForestClassifier(20), digits.data, digits.target))
print("30", cross_val_score(RandomForestClassifier(30), digits.data, digits.target))
print("40", cross_val_score(RandomForestClassifier(40), digits.data, digits.target))
print("50", cross_val_score(RandomForestClassifier(50), digits.data, digits.target))
print("70", cross_val_score(RandomForestClassifier(70), digits.data, digits.target))
print("90", cross_val_score(RandomForestClassifier(90), digits.data, digits.target))

10 [0.89166667 0.81944444 0.91086351 0.93871866 0.88857939]
20 [0.94166667 0.88611111 0.93314763 0.96935933 0.90529248]
30 [0.91944444 0.89722222 0.9637883  0.9637883  0.91643454]
40 [0.92222222 0.92222222 0.94986072 0.95543175 0.91364903]
50 [0.93333333 0.89722222 0.95543175 0.95543175 0.93314763]
70 [0.93611111 0.91944444 0.94986072 0.95543175 0.92200557]
90 [0.92777778 0.91944444 0.96657382 0.95543175 0.91643454]
