In [1]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
df = pd.DataFrame(iris.data, columns= iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x : iris.target_names[x])
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size= 0.25)

In [11]:
from sklearn.svm import SVC
model =SVC()
model = SVC(kernel= "rbf", C= 30, gamma= "auto")
model.fit(x_train, y_train)
model.score(x_test, y_test)

1.0

In [15]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel= "linear", C=10, gamma= "auto"), iris.data, iris.target, cv= 5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [18]:
cross_val_score(SVC(kernel= "rbf", C=10, gamma= "auto"), iris.data, iris.target, cv= 5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [19]:
cross_val_score(SVC(kernel= "rbf", C=20, gamma= "auto"), iris.data, iris.target, cv= 5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [25]:
kernels = ['rbf', 'linear']
c = [1, 10, 20, 30]
avg_score = {}
import numpy as np
for kval in kernels:
    for cval in c:
        cv_score = cross_val_score(SVC(kernel = kval, C = cval, gamma = "auto"), iris.data, iris.target, cv = 5)
        avg_score[kval + "_" + str(cval)]= np.average(cv_score)

avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'rbf_30': 0.96,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'linear_30': 0.96}

In [26]:
# in above case the time complexity is O(n2)
# so this is not a good approach as many time s the iteration is going to increase
# instead of this gridsearch csv can be used

In [28]:
from sklearn.model_selection import GridSearchCV

gd = GridSearchCV(SVC(gamma="auto"), {'C' : [1,10,2, 20], 'kernel' : ['linear', 'rbf', 'poly']}, cv = 5, return_train_score = False)

gd.fit(iris.data, iris.target)
gd.cv_results_


{'mean_fit_time': array([0.00061688, 0.00077748, 0.00141821, 0.00099249, 0.00122542,
        0.00409107, 0.00119634, 0.000741  , 0.00206461, 0.00099659,
        0.000598  , 0.00518255]),
 'std_fit_time': array([5.04914345e-04, 7.38283694e-04, 7.49312895e-04, 5.18702400e-05,
        3.90145744e-04, 2.53305752e-03, 3.98182965e-04, 6.18430386e-04,
        1.50491855e-03, 2.61174468e-07, 4.88266172e-04, 4.24717730e-03]),
 'mean_score_time': array([0.00077987, 0.00042462, 0.00037923, 0.        , 0.00038757,
        0.00039892, 0.00079722, 0.00070858, 0.00060096, 0.        ,
        0.00039868, 0.00019965]),
 'std_score_time': array([0.0003921 , 0.00052063, 0.00046545, 0.        , 0.0004749 ,
        0.00048858, 0.00074577, 0.0005899 , 0.00049071, 0.        ,
        0.00048829, 0.0003993 ]),
 'param_C': masked_array(data=[1, 1, 1, 10, 10, 10, 2, 2, 2, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
   